using CapShop.AuthService.Dtos;
using CapShop.AuthService.Models;
using CapShop.AuthService.Repositories;

namespace CapShop.AuthService.Services;

public class AccountService : IAccountService
{
    private readonly IUserRepository _users;
    private readonly IJwtTokenService _jwt;
    private readonly ITwoFactorService _twoFactor;
    private readonly ILogger<AccountService> _logger;

    public AccountService(
        IUserRepository users,
        IJwtTokenService jwt,
        ITwoFactorService twoFactor,
        ILogger<AccountService> logger)
    {
        _users = users;
        _jwt = jwt;
        _twoFactor = twoFactor;
        _logger = logger;
    }

    public async Task<string> SignupAsync(SignUpRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Email) || string.IsNullOrWhiteSpace(request.Password))
            throw new ArgumentException("Email and password are required.");

        var email = request.Email.Trim().ToLowerInvariant();

        if (await _users.ExistsByEmailAsync(email))
            throw new InvalidOperationException("Email already registered.");

        var user = new User
        {
            Id = Guid.NewGuid(),
            FullName = request.FullName.Trim(),
            Email = email,
            PhoneNumber = request.PhoneNumber.Trim(),
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(request.Password),
            Role = UserRole.Customer
        };

        await _users.AddAsync(user);

        _logger.LogInformation("New customer registered: {Email}", email);
        return "Signup successful.";
    }

    public async Task<AuthResponse> LoginAsync(LoginRequest request)
    {
        var email = request.Email.Trim().ToLowerInvariant();
        var user = await _users.FindByEmailAsync(email);

        if (user is null || !user.IsActive)
        {
            _logger.LogWarning("Failed login attempt for: {Email}", email);
            throw new UnauthorizedAccessException("Invalid credentials.");
        }

        if (!BCrypt.Net.BCrypt.Verify(request.Password, user.PasswordHash))
        {
            _logger.LogWarning("Invalid password for: {Email}", email);
            throw new UnauthorizedAccessException("Invalid credentials.");
        }

        if (!user.TwoFactorEnabled)
        {
            _logger.LogInformation("Successful login: {Email}, Role: {Role}", email, user.Role);
            return new AuthResponse
            {
                Token = _jwt.GenerateToken(user),
                Role = user.Role.ToString()
            };
        }

        // 2FA required — send code if Email or SMS, then return challenge
        if (user.TwoFactorMethod is TwoFactorMethod.Email or TwoFactorMethod.Sms)
            await _twoFactor.SendOtpAsync(user.Id, user.TwoFactorMethod);

        var tempToken = _jwt.GenerateTempToken(user.Id, user.TwoFactorMethod);

        _logger.LogInformation("2FA challenge issued for: {Email}, Method: {Method}", email, user.TwoFactorMethod);

        return new AuthResponse
        {
            RequiresTwoFactor = true,
            TempToken = tempToken,
            TwoFactorMethod = user.TwoFactorMethod.ToString()
        };
    }

    public async Task<AuthResponse> VerifyTwoFactorAsync(VerifyTwoFactorRequest request)
    {
        var payload = _jwt.ValidateTempToken(request.TempToken);
        if (payload is null)
            throw new UnauthorizedAccessException("Invalid or expired session. Please log in again.");

        var user = await _users.FindByIdAsync(payload.UserId);
        if (user is null || !user.IsActive)
            throw new UnauthorizedAccessException("User not found.");

        var verified = payload.Method == TwoFactorMethod.Authenticator
            ? await _twoFactor.VerifyTotpCodeAsync(user.Id, request.Code)
            : await _twoFactor.VerifyOtpCodeAsync(user.Id, request.Code);

        if (!verified)
            throw new UnauthorizedAccessException("Invalid or expired code.");

        _logger.LogInformation("2FA verified for: {Email}", user.Email);

        return new AuthResponse
        {
            Token = _jwt.GenerateToken(user),
            Role = user.Role.ToString()
        };
    }

    public async Task ResendTwoFactorCodeAsync(string tempToken)
    {
        var payload = _jwt.ValidateTempToken(tempToken);
        if (payload is null)
            throw new UnauthorizedAccessException("Invalid or expired session. Please log in again.");

        if (payload.Method is TwoFactorMethod.Authenticator)
            throw new InvalidOperationException("Authenticator codes are generated by your app. No resend needed.");

        await _twoFactor.SendOtpAsync(payload.UserId, payload.Method);
    }
}