using CapShop.AuthService.Dtos;
using CapShop.AuthService.Models;
using CapShop.AuthService.Repositories;
using Microsoft.AspNetCore.Hosting;

namespace CapShop.AuthService.Services;

public class AccountService : IAccountService
{
    private const long MaxAvatarBytes = 2 * 1024 * 1024;

    private readonly IUserRepository _users;
    private readonly IJwtTokenService _jwt;
    private readonly ITwoFactorService _twoFactor;
    private readonly IWebHostEnvironment _env;
    private readonly ILogger<AccountService> _logger;

    public AccountService(
        IUserRepository users,
        IJwtTokenService jwt,
        ITwoFactorService twoFactor,
        IWebHostEnvironment env,
        ILogger<AccountService> logger)
    {
        _users = users;
        _jwt = jwt;
        _twoFactor = twoFactor;
        _env = env;
        _logger = logger;
    }

    public async Task<string> SignupAsync(SignUpRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Email) || string.IsNullOrWhiteSpace(request.Password))
            throw new ArgumentException("Email and password are required.");

        var email = request.Email.Trim().ToLowerInvariant();

        if (await _users.ExistsByEmailAsync(email))
            throw new InvalidOperationException("Email already registered.");

        var user = new User
        {
            Id = Guid.NewGuid(),
            FullName = request.FullName.Trim(),
            Email = email,
            PhoneNumber = request.PhoneNumber.Trim(),
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(request.Password),
            Role = UserRole.Customer
        };

        await _users.AddAsync(user);

        _logger.LogInformation("New customer registered: {Email}", email);
        return "Signup successful.";
    }

    public async Task<AuthResponse> LoginAsync(LoginRequest request)
    {
        var email = request.Email.Trim().ToLowerInvariant();
        var user = await _users.FindByEmailAsync(email);

        if (user is null || !user.IsActive)
        {
            _logger.LogWarning("Failed login attempt for: {Email}", email);
            throw new UnauthorizedAccessException("Invalid credentials.");
        }

        if (!BCrypt.Net.BCrypt.Verify(request.Password, user.PasswordHash))
        {
            _logger.LogWarning("Invalid password for: {Email}", email);
            throw new UnauthorizedAccessException("Invalid credentials.");
        }

        if (!user.TwoFactorEnabled)
        {
            _logger.LogInformation("Successful login: {Email}, Role: {Role}", email, user.Role);
            return new AuthResponse
            {
                Token = _jwt.GenerateToken(user),
                Role = user.Role.ToString()
            };
        }

        // 2FA required — send code if Email or SMS, then return challenge
        if (user.TwoFactorMethod is TwoFactorMethod.Email or TwoFactorMethod.Sms)
            await _twoFactor.SendOtpAsync(user.Id, user.TwoFactorMethod);

        var tempToken = _jwt.GenerateTempToken(user.Id, user.TwoFactorMethod);

        _logger.LogInformation("2FA challenge issued for: {Email}, Method: {Method}", email, user.TwoFactorMethod);

        return new AuthResponse
        {
            RequiresTwoFactor = true,
            TempToken = tempToken,
            TwoFactorMethod = user.TwoFactorMethod.ToString()
        };
    }

    public async Task<AuthResponse> VerifyTwoFactorAsync(VerifyTwoFactorRequest request)
    {
        var payload = _jwt.ValidateTempToken(request.TempToken);
        if (payload is null)
            throw new UnauthorizedAccessException("Invalid or expired session. Please log in again.");

        var user = await _users.FindByIdAsync(payload.UserId);
        if (user is null || !user.IsActive)
            throw new UnauthorizedAccessException("User not found.");

        var verified = payload.Method == TwoFactorMethod.Authenticator
            ? await _twoFactor.VerifyTotpCodeAsync(user.Id, request.Code)
            : await _twoFactor.VerifyOtpCodeAsync(user.Id, request.Code);

        if (!verified)
            throw new UnauthorizedAccessException("Invalid or expired code.");

        _logger.LogInformation("2FA verified for: {Email}", user.Email);

        return new AuthResponse
        {
            Token = _jwt.GenerateToken(user),
            Role = user.Role.ToString()
        };
    }

    public async Task ResendTwoFactorCodeAsync(string tempToken)
    {
        var payload = _jwt.ValidateTempToken(tempToken);
        if (payload is null)
            throw new UnauthorizedAccessException("Invalid or expired session. Please log in again.");

        if (payload.Method is TwoFactorMethod.Authenticator)
            throw new InvalidOperationException("Authenticator codes are generated by your app. No resend needed.");

        await _twoFactor.SendOtpAsync(payload.UserId, payload.Method);
    }

    public async Task<ProfileResponse> GetProfileAsync(Guid userId)
    {
        var user = await _users.FindByIdAsync(userId)
            ?? throw new KeyNotFoundException("User not found.");
        return MapProfile(user);
    }

    public async Task<ProfileResponse> UpdateProfileAsync(Guid userId, UpdateProfileRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.FullName))
            throw new ArgumentException("Full name is required.");

        var user = await _users.FindByIdAsync(userId)
            ?? throw new KeyNotFoundException("User not found.");

        user.FullName = request.FullName.Trim();
        user.PhoneNumber = request.PhoneNumber?.Trim() ?? string.Empty;

        await _users.UpdateAsync(user);

        _logger.LogInformation("Profile updated for user {UserId}", userId);

        return MapProfile(user);
    }

    public async Task ChangePasswordAsync(Guid userId, ChangePasswordRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.NewPassword) || request.NewPassword.Length < 6)
            throw new ArgumentException("New password must be at least 6 characters.");

        var user = await _users.FindByIdAsync(userId)
            ?? throw new KeyNotFoundException("User not found.");

        if (!BCrypt.Net.BCrypt.Verify(request.CurrentPassword, user.PasswordHash))
            throw new ArgumentException("Current password is incorrect.");

        user.PasswordHash = BCrypt.Net.BCrypt.HashPassword(request.NewPassword);
        await _users.UpdateAsync(user);

        _logger.LogInformation("Password changed for user {UserId}", userId);
    }

    public async Task<ProfileResponse> SetAvatarAsync(
        Guid userId,
        Stream fileStream,
        string contentType,
        long length)
    {
        if (length <= 0 || length > MaxAvatarBytes)
            throw new ArgumentException("Image must be between 1 byte and 2 MB.");

        var ext = contentType.ToLowerInvariant() switch
        {
            "image/jpeg" or "image/jpg" => ".jpg",
            "image/png" => ".png",
            "image/webp" => ".webp",
            "image/gif" => ".gif",
            _ => throw new ArgumentException("Only JPEG, PNG, WebP, and GIF images are allowed.")
        };

        var user = await _users.FindByIdAsync(userId)
            ?? throw new KeyNotFoundException("User not found.");

        TryDeletePhysicalFile(user.ProfilePictureUrl);

        var webRoot = _env.WebRootPath ?? Path.Combine(_env.ContentRootPath, "wwwroot");
        var avatarsDir = Path.Combine(webRoot, "avatars");
        Directory.CreateDirectory(avatarsDir);

        var fileName = $"{userId:N}{ext}";
        var physicalPath = Path.Combine(avatarsDir, fileName);

        await using (var output = File.Create(physicalPath))
        {
            await fileStream.CopyToAsync(output);
        }

        user.ProfilePictureUrl = $"/avatars/{fileName}";
        await _users.UpdateAsync(user);

        _logger.LogInformation("Avatar updated for user {UserId}", userId);

        return MapProfile(user);
    }

    public async Task<ProfileResponse> RemoveAvatarAsync(Guid userId)
    {
        var user = await _users.FindByIdAsync(userId)
            ?? throw new KeyNotFoundException("User not found.");

        TryDeletePhysicalFile(user.ProfilePictureUrl);
        user.ProfilePictureUrl = null;
        await _users.UpdateAsync(user);

        _logger.LogInformation("Avatar removed for user {UserId}", userId);

        return MapProfile(user);
    }

    private void TryDeletePhysicalFile(string? relativeUrl)
    {
        if (string.IsNullOrEmpty(relativeUrl) || !relativeUrl.StartsWith("/avatars/", StringComparison.OrdinalIgnoreCase))
            return;

        var fileName = Path.GetFileName(relativeUrl);
        if (string.IsNullOrEmpty(fileName) || fileName.Contains("..", StringComparison.Ordinal))
            return;

        var webRoot = _env.WebRootPath ?? Path.Combine(_env.ContentRootPath, "wwwroot");
        var path = Path.Combine(webRoot, "avatars", fileName);

        try
        {
            if (File.Exists(path))
                File.Delete(path);
        }
        catch (IOException ex)
        {
            _logger.LogWarning(ex, "Could not delete avatar file {Path}", path);
        }
    }

    private static ProfileResponse MapProfile(User u) => new()
    {
        FullName = u.FullName,
        Email = u.Email,
        PhoneNumber = u.PhoneNumber,
        Role = u.Role.ToString(),
        ProfilePictureUrl = u.ProfilePictureUrl
    };
}